# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logging.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'logging.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlogging.proto\x12\x07logging\"\'\n\nLogRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\x1d\n\x0bLogResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\" \n\x0cLogsResponse\x12\x10\n\x08messages\x18\x01 \x03(\t2t\n\x0eLoggingService\x12\x30\n\x03Log\x12\x13.logging.LogRequest\x1a\x14.logging.LogResponse\x12\x30\n\x07GetLogs\x12\x0e.logging.Empty\x1a\x15.logging.LogsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logging_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGREQUEST']._serialized_start=26
  _globals['_LOGREQUEST']._serialized_end=65
  _globals['_LOGRESPONSE']._serialized_start=67
  _globals['_LOGRESPONSE']._serialized_end=96
  _globals['_EMPTY']._serialized_start=98
  _globals['_EMPTY']._serialized_end=105
  _globals['_LOGSRESPONSE']._serialized_start=107
  _globals['_LOGSRESPONSE']._serialized_end=139
  _globals['_LOGGINGSERVICE']._serialized_start=141
  _globals['_LOGGINGSERVICE']._serialized_end=257
# @@protoc_insertion_point(module_scope)
