version: '3.8'

services:
  consul:
    image: hashicorp/consul:1.18
    container_name: consul-server
    ports:
      - "8500:8500"
      - "8600:8600/tcp" 
      - "8600:8600/udp" 
    command: "agent -server -ui -dev -client=0.0.0.0 -bootstrap-expect=1"
    networks:
      - consul_network

networks:
  consul_network:
    driver: bridge