version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka1:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1

      # слушает внутри контейнера на 9092,
      # а “рекламирует” себя BROKER-TO-BROKER как kafka1:9092
      # и EXTERNAL клиентам (FastAPI) как localhost:9092
      KAFKA_LISTENERS: \
        PLAINTEXT://0.0.0.0:9092,\
        BROKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: \
        PLAINTEXT://localhost:9092,\
        BROKER://kafka1:9093

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: \
        PLAINTEXT:PLAINTEXT,\
        BROKER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER

      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  kafka2:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka2
    depends_on:
      - zookeeper
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: \
        PLAINTEXT://0.0.0.0:9092,\
        BROKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: \
        PLAINTEXT://localhost:9093,\
        BROKER://kafka2:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: \
        PLAINTEXT:PLAINTEXT,\
        BROKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER

      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  kafka3:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka3
    depends_on:
      - zookeeper
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENERS: \
        PLAINTEXT://0.0.0.0:9092,\
        BROKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: \
        PLAINTEXT://localhost:9094,\
        BROKER://kafka3:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: \
        PLAINTEXT:PLAINTEXT,\
        BROKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER

      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

networks:
  default:
    driver: bridge